/**
 * Do not edit directly
 * Generated on Mon, 12 Dec 2022 12:38:03 GMT
 */

const ColorNeutralBase = "0, 0%";
const ColorPrimaryBase = "209, 100%";
const ColorSecondaryBase = "79, 100%";
const ColorComplementaryBase = "284, 100%";
const ColorPositiveBase = "144, 100%";
const ColorAlertBase = "57, 100%";
const ColorNegativeBase = "7, 100%"
const ColorInformativeBase = "190, 100%";

module.exports = {
  "Neutral10": `hsla(${ColorNeutralBase}, 99%, 1)`,
  "Neutral50": `hsla(${ColorNeutralBase}, 96%, 1)`,
  "Neutral100": `hsla(${ColorNeutralBase}, 90%, 1)`,
  "Neutral200": `hsla(${ColorNeutralBase}, 80%, 1)`,
  "Neutral300": `hsla(${ColorNeutralBase}, 70%, 1)`,
  "Neutral400": `hsla(${ColorNeutralBase}, 60%, 1)`,
  "Neutral500": `hsla(${ColorNeutralBase}, 50%, 1)`,
  "Neutral600": `hsla(${ColorNeutralBase}, 40%, 1)`,
  "Neutral700": `hsla(${ColorNeutralBase}, 30%, 1)`,
  "Neutral800": `hsla(${ColorNeutralBase}, 20%, 1)`,
  "Neutral900": `hsla(${ColorNeutralBase}, 10%, 1)`,
  "Primary10": `hsla(${ColorPrimaryBase}, 91%, 1)`,
  "Primary100": `hsla(${ColorPrimaryBase}, 81%, 1)`,
  "Primary200": `hsla(${ColorPrimaryBase}, 71%, 1)`,
  "Primary300": `hsla(${ColorPrimaryBase}, 61%, 1)`,
  "Primary400": `hsla(${ColorPrimaryBase}, 51%, 1)`,
  "Primary500": `hsla(${ColorPrimaryBase}, 41%, 1)`,
  "Primary600": `hsla(${ColorPrimaryBase}, 31%, 1)`,
  "Primary700": `hsla(${ColorPrimaryBase}, 21%, 1)`,
  "Primary800": `hsla(${ColorPrimaryBase}, 11%, 1)`,
  "Primary900": `hsla(${ColorPrimaryBase}, 1%, 1)"`,
  "Secondary10": `hsla(${ColorSecondaryBase}, 96%, 1)`,
  "Secondary100": `hsla(${ColorSecondaryBase}, 86%, 1)`,
  "Secondary200": `hsla(${ColorSecondaryBase}, 76%, 1)`,
  "Secondary300": `hsla(${ColorSecondaryBase}, 66%, 1)`,
  "Secondary400": `hsla(${ColorSecondaryBase}, 56%, 1)`,
  "Secondary500": `hsla(${ColorSecondaryBase}, 46%, 1)`,
  "Secondary600": `hsla(${ColorSecondaryBase}, 36%, 1)`,
  "Secondary700": `hsla(${ColorSecondaryBase}, 26%, 1)`,
  "Secondary800": `hsla(${ColorSecondaryBase}, 16%, 1)`,
  "Secondary900": `hsla(${ColorSecondaryBase}, 6%, 1)`,
  "Accent10": `hsla(${ColorComplementaryBase}, 95%, 1)`,
  "Accent100": `hsla(${ColorComplementaryBase}, 85%, 1)`,
  "Accent200": `hsla(${ColorComplementaryBase}, 75%, 1)`,
  "Accent300": `hsla(${ColorComplementaryBase}, 65%, 1)`,
  "Accent400": `hsla(${ColorComplementaryBase}, 55%, 1)`,
  "Accent500": `hsla(${ColorComplementaryBase}, 45%, 1)`,
  "Accent600": `hsla(${ColorComplementaryBase}, 35%, 1)`,
  "Accent700": `hsla(${ColorComplementaryBase}, 25%, 1)`,
  "Accent800": `hsla(${ColorComplementaryBase}, 15%, 1)`,
  "Accent900": `hsla(${ColorComplementaryBase}, 5%, 1)`,
  "FeedbacksPositive10": `hsla(${ColorPositiveBase}, 95%, 1)`,
  "FeedbacksPositive100": `hsla(${ColorPositiveBase}, 85%, 1)`,
  "FeedbacksPositive200": `hsla(${ColorPositiveBase}, 75%, 1)`,
  "FeedbacksPositive300": `hsla(${ColorPositiveBase}, 65%, 1)`,
  "FeedbacksPositive400": `hsla(${ColorPositiveBase}, 55%, 1)`,
  "FeedbacksPositive500": `hsla(${ColorPositiveBase}, 45%, 1)`,
  "FeedbacksPositive600": `hsla(${ColorPositiveBase}, 35%, 1)`,
  "FeedbacksPositive700": `hsla(${ColorPositiveBase}, 25%, 1)`,
  "FeedbacksPositive800": `hsla(${ColorPositiveBase}, 15%, 1)`,
  "FeedbacksPositive900": `hsla(${ColorPositiveBase}, 5%, 1)`,
  "FeedbacksWarning10": `hsla(${ColorAlertBase}, 95%, 1)`,
  "FeedbacksWarning100": `hsla(${ColorAlertBase}, 85%, 1)`,
  "FeedbacksWarning200": `hsla(${ColorAlertBase}, 75%, 1)`,
  "FeedbacksWarning300": `hsla(${ColorAlertBase}, 65%, 1)`,
  "FeedbacksWarning400": `hsla(${ColorAlertBase}, 55%, 1)`,
  "FeedbacksWarning500": `hsla(${ColorAlertBase}, 45%, 1)`,
  "FeedbacksWarning600": `hsla(${ColorAlertBase}, 35%, 1)`,
  "FeedbacksWarning700": `hsla(${ColorAlertBase}, 25%, 1)`,
  "FeedbacksWarning800": `hsla(${ColorAlertBase}, 15%, 1)`,
  "FeedbacksWarning900": `hsla(${ColorAlertBase}, 5%, 1)`,
  "FeedbacksNegative10": `hsla(${ColorAlertBase}, 95%, 1)`,
  "FeedbacksNegative100": `hsla(${ColorNegativeBase}, 85%, 1)`,
  "FeedbacksNegative200": `hsla(${ColorNegativeBase}, 75%, 1)`,
  "FeedbacksNegative300": `hsla(${ColorNegativeBase}, 65%, 1)`,
  "FeedbacksNegative400": `hsla(${ColorNegativeBase}, 55%, 1)`,
  "FeedbacksNegative500": `hsla(${ColorNegativeBase}, 45%, 1)`,
  "FeedbacksNegative600": `hsla(${ColorNegativeBase}, 35%, 1)`,
  "FeedbacksNegative700": `hsla(${ColorNegativeBase}, 25%, 1)`,
  "FeedbacksNegative800": `hsla(${ColorNegativeBase}, 15%, 1)`,
  "FeedbacksNegative900": `hsla(${ColorNegativeBase}, 5%, 1)`,
  "FeedbacksInformative10": `hsla(${ColorInformativeBase}, 95%, 1)`,
  "FeedbacksInformative100": `hsla(${ColorInformativeBase}, 85%, 1)`,
  "FeedbacksInformative200": `hsla(${ColorInformativeBase}, 75%, 1)`,
  "FeedbacksInformative300": `hsla(${ColorInformativeBase}, 65%, 1)`,
  "FeedbacksInformative400": `hsla(${ColorInformativeBase}, 55%, 1)`,
  "FeedbacksInformative500": `hsla(${ColorInformativeBase}, 45%, 1)`,
  "FeedbacksInformative600": `hsla(${ColorInformativeBase}, 35%, 1)`,
  "FeedbacksInformative700": `hsla(${ColorInformativeBase}, 25%, 1)`,
  "FeedbacksInformative800": `hsla(${ColorInformativeBase}, 15%, 1)`,
  "FeedbacksInformative900": `hsla(${ColorInformativeBase}, 5%, 1)`,
};